server:
  port: 9002

spring:
  application:
    name:link-server
  datasource:
    url: jdbc:mysql://49.232.223.214:3306/index?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root2
    password: root2
  data:
    redis:
      host: 49.232.223.214
      password: root_1023

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
#      todo 临时关闭eureka
    enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html

